# Generated by Django 4.1.7 on 2023-05-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojisteny',
            name='cislo_popisne',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pojisteny',
            name='mesto',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pojisteny',
            name='psc',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pojisteny',
            name='telefon',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pojisteny',
            name='ulice',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
