# Generated by Django 4.2.1 on 2023-05-09 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0002_pojisteny_cislo_popisne_pojisteny_mesto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojisteni',
            name='pojisteny',
        ),
        migrations.RemoveField(
            model_name='pojisteni',
            name='popis',
        ),
        migrations.AddField(
            model_name='pojisteni',
            name='castka',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='pojisteni',
            name='platnost_do',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pojisteni',
            name='platnost_od',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pojisteni',
            name='predmet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='pojisteni',
            table='pojisteni',
        ),
    ]
