# Generated by Django 4.2.1 on 2023-05-09 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0003_remove_pojisteni_pojisteny_remove_pojisteni_popis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojisteni',
            name='pojisteny',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pojisteni_set', to='pojisteni.pojisteny'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='castka',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='nazev',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='platnost_do',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='platnost_od',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='predmet',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
