# Generated by Django 4.2.1 on 2023-05-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0004_pojisteni_pojisteny_alter_pojisteni_castka_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pojisteni',
            old_name='pojisteny',
            new_name='pojisteny_objekt',
        ),
    ]
